### ISSUE TITLE
Data type of amount, price in clob

### ISSUE THREAD

**Issue by shanhashcah** [hroptatyr/clob#14]
Hi @hroptatyr 

In clob  as of now we are passing amount, price value as double type, will we be allowed to pass long type value. I mean suppose we want to  pass  million/billion value for amount/price then would we be able to pass it?

A big Thank You

**Comment by hroptatyr** [comment]
Hi,
_Decimal64's largest exact number (signficand) is 9 999 999 999 999 999, so that's nearly 10 quadrillion, you cannot have a fraction though.  Similarly the largest number with a 1/10th fraction would be 999 999 999 999 999.9, etc.

If you use double instead of _Decimal64 for speed reasons the largest exactly representable number would be 9 007 199 254 740 992, so only 9 quadrillion.  It's not easy to come up with the largest number with a tenth fraction because .5 only uses one bit, whereas all other 1/10ths require more bits.

**Comment by shanhashcah** [comment]
Ok Sir..Let me chech then I'll reply.

**Comment by shanhashcah** [comment]
ok..
